application: office-quotes
version: 1
runtime: python27
api_version: 1
threadsafe: yes

builtins:
- remote_api: on

inbound_services:
- warmup

handlers:
- url: /_ah/queue/deferred
  script: djangoappengine.deferred.handler.application
  login: admin

- url: /_ah/stats/.*
  script: djangoappengine.appstats.application

- url: /media/admin
  static_dir: django/contrib/admin/media
  expiration: '0'

- url: /static
  static_dir: static
 
- url: /.*
  script: djangoappengine.main.application
  

###########################################   Managed VM Settings   ######################################
runtime: custom
vm: true
entrypoint: custom

manual_scaling:
  instances: 1
  
handlers:
- url: /static
  static_dir: static

- url: /.*
  script: DjangoVM.wsgi.application
  